config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  post 'rooms/create' => 'rooms#create', as: 'new_room'
  devise_for :users
	resources :rooms, only: [:show, :destroy]
	delete 'message/:id' => 'rooms#message_destroy', as: 'message'
	get 'rooms/check_password/:room_id' => 'rooms#check_password', as: 'check_password'
	post 'rooms/create_session' => 'rooms#create_session', as: 'create_session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :room
	belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def email_required?
  	false
  end
  def email_changed?
  	false
  end
  def will_save_change_to_email?
  	false
	end

	validates :name, uniqueness: true
	has_many :messages
	has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		session[:room_id] = []
		root_path
	end


	protected

  def configure_permitted_parameters
    added_attrs = [ :name ]
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!
  def index
    @rooms = Room.all
  end

  def show
  	@room = Room.find(params[:id])
    unless @room.password == '' || session[:room_id].include?(@room.id)
      redirect_to root_path
    end
  	@messages = Message.where(room_id: @room.id).order('id desc')
    gon.room_id = @room.id
  end

  def create
  	room = Room.create(name: params['room_name'], password: params['room_password'])
    create_session(room.id)
  	redirect_to room_path(room.id)
  end

  def destroy
  	room = Room.find(params[:id])
  	room.destroy
  	redirect_to root_path
  end

 	def message_destroy
 		message = Message.find(params[:id])
 		room = Room.find(message.room.id)
 		message.destroy
 		redirect_to room_path(room.id)
 	end

  def check_password
    room = Room.find(params['room_id'])
    if room.password != '' && session[:room_id].include?(room.id) == false
      render json: room.password
    end
  end
  # 引数はパラメータも受け取れる
  def create_session(room_id=params[:room_id].to_i)
    session[:room_id].push(room_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <script type="text/javascript" src="//cdn.webrtc.ecl.ntt.com/skyway-latest.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </header>
    <% if user_signed_in? %>
      
    <% end %>
    <%= yield %>
  </body>
  
</html>

app/views/rooms/_message.html.erb
<div class="message">
  <p><%= message.message %></p>
  <% if current_user.id == 1 %>
  	<%= link_to "削除", message_path(message.id), method: :delete %>
  <% end %>
</div>

app/views/rooms/index.html.erb
<h2>チャット</h2>
<h3>部屋作成</h3>
<form method="post" action="/rooms/create">
    <%= hidden_field_tag "authenticity_token", form_authenticity_token %>
	<input type="text" placeholder="Room名" name="room_name" id="room_name" autocomplete="off">
	<input type="hidden" id="password" name="room_password">
</form>

<h3>部屋一覧</h3>
<% @rooms.each do |room| %>
	<div>
		<!-- <%= link_to room.name, room_path(room.id) %> -->
		<span data-room="<%= room.id %>"><%= room.name %></span>
		<% if current_user.id == 1 %>
			<%= link_to "削除", room_path(room.id), method: :delete %>
		<% end %>
	</div>
<% end %>

<script>
	$(function() {
    $("input").on("keydown", function(e) {
        if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
        	if ($('#room_name').val() != '') {
		        password = window.prompt('他の人に見られないようにパスワードを入力(空なら設定しない)');
		        $('#password').val(password);
		      } else {
		      	return false;
		      }
        } else {
          return true;
        }
    });

    $(document).on('click', 'span', function() {
    	var data = $(this).data('room');
    	$.ajax({
    		url: './rooms/check_password/' + data,
    		type: 'get',
    		dataType: 'text'
    	})
    	.done(function(e) {
    		if (e) {
    			password = window.prompt('パスワードを入力してください');
    			if (e == password) {
    				$.ajax({
    					url: './rooms/create_session',
    					type: 'post',
    					data: {
                "room_id": data
            	}
    				})
    				.done(function() {
	    				window.location.href = './rooms/' + data;
    				})
    			} else {
    				alert('パスワードが違います。');
    			}
    		} else {
    			window.location.href = './rooms/' + data;
    		}
    	})
    })
	})
</script>

app/views/rooms/show.html.erb
<div class="container">
  <!-- Video area -->
  <div class="pure-u-2-3" id="video-container">
    <div id="their-videos"></div>
    <div>
      <label id="my-label"></label>
      <video id="my-video" muted="true" autoplay playsinline></video>
    </div>
  </div>

  <!-- Steps -->
  <div class="">
    <h3>Settigns</h3>

    <div class="select">
      <label for="audioSource">Audio input source: </label><select id="audioSource"></select>
    </div>

    <div class="select">
      <label for="videoSource">Video source: </label><select id="videoSource"></select>
    </div>

    
	<h3>Action</h3>
    <div id="step2">
      <button id="participate" class="btn btn-success" value="<%= @room.name %>">参加する</button>
	  <button id="end-call" class="btn btn-warning">Tel Off</button>
	  <%= link_to "部屋を出る", root_path , class: "btn btn-default" %>
    </div>

  </div>
</div>

<script>
	const skyway = new SkyWay()

	$('#participate').on('click', (e)=>{
		const roomName = e.target.value;
		skyway.makeCall(roomName);
	});

	$('#end-call').on('click', (e)=>{
		skyway.endCall();
	});
</script>